context:
  version: "1.46.0"

package:
  name: process-compose
  version: ${{ version }}

source:
  url: https://github.com/F1bonacc1/process-compose/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 709399d33dbc1d9ec3bf3bbf4533bf5a2351e57ece76a2f645fa8463859bb80c
  target_directory: src

build:
  number: 0
  script:
    - cd src
    - go-licenses save ./src --save_path ../library_licenses
    - if: win
      then: >
        go build
        -ldflags="-s -w -X github.com/f1bonacc1/process-compose/src/config.Version=v${{ version }}"
        -v -o %LIBRARY_BIN%\process-compose.exe ./src
      else: >
        go build
        -ldflags="-s -w -X github.com/f1bonacc1/process-compose/src/config.Version=v${{ version }}"
        -v -o $PREFIX/bin/process-compose ./src
    - if: unix
      then:
        - mkdir -p $PREFIX/share/bash-completion/completions
        - process-compose completion bash > $PREFIX/share/bash-completion/completions/process-compose
        - mkdir -p $PREFIX/share/zsh/site-functions
        - process-compose completion zsh > $PREFIX/share/zsh/site-functions/_process-compose
        - mkdir -p $PREFIX/share/fish/vendor_completions.d
        - process-compose completion fish > $PREFIX/share/fish/vendor_completions.d/process-compose.fish

requirements:
  build:
    - ${{ stdlib("c") }}
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - process-compose version
      - process-compose --help

about:
  homepage: https://f1bonacc1.github.io/process-compose/
  license: Apache-2.0
  license_file:
    - LICENSE
    - library_licenses/
  summary: Process Compose is a simple and flexible scheduler and orchestrator to manage non-containerized applications.
  description: |
    Because sometimes you just don't want to deal with docker files, volume definitions, networks and docker registries. 
    Since it's written in Go, Process Compose is a single binary file and has no other dependencies.

    Once installed, you just need to describe your workflow using a simple YAML schema in a file called process-compose.yaml:

    ```yaml
    version: "0.5"

    processes:
      hello:
        command: echo 'Hello World from Process Compose'
    ````

    And start it by running process-compose up from your terminal.

  repository: https://github.com/F1bonacc1/process-compose
  documentation: https://f1bonacc1.github.io/process-compose/launcher/

extra:
  recipe-maintainers:
    - wolfv
